// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteAPI.Data;

#nullable disable

namespace RestauranteAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615142218_AddMaisProdutos")]
    partial class AddMaisProdutos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("RestauranteAPI.Models.ItemPedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PedidoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProdutoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ItemPedidos");
                });

            modelBuilder.Entity("RestauranteAPI.Models.Pedido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SetorPedido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StatusPedido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("numMesa")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("RestauranteAPI.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoProduto")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("ValorProduto")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomeProduto = "Frango Grelhado",
                            TipoProduto = "Prato",
                            ValorProduto = 28.0
                        },
                        new
                        {
                            Id = 2,
                            NomeProduto = "Filé ao Molho Madeira",
                            TipoProduto = "Prato",
                            ValorProduto = 45.0
                        },
                        new
                        {
                            Id = 3,
                            NomeProduto = "Suco de Laranja",
                            TipoProduto = "Bebida",
                            ValorProduto = 8.0
                        },
                        new
                        {
                            Id = 4,
                            NomeProduto = "Refrigerante Cola",
                            TipoProduto = "Bebida",
                            ValorProduto = 6.0
                        },
                        new
                        {
                            Id = 5,
                            NomeProduto = "Salada Caesar",
                            TipoProduto = "Prato",
                            ValorProduto = 22.0
                        },
                        new
                        {
                            Id = 6,
                            NomeProduto = "Água Mineral",
                            TipoProduto = "Bebida",
                            ValorProduto = 4.0
                        });
                });

            modelBuilder.Entity("RestauranteAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("perfil")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            email = "funcionario@rest.com",
                            name = "Funcionario",
                            perfil = "Funcionario",
                            senha = "123456"
                        },
                        new
                        {
                            Id = 2,
                            email = "cozinha@rest.com",
                            name = "Cozinha",
                            perfil = "Cozinha",
                            senha = "123456"
                        },
                        new
                        {
                            Id = 3,
                            email = "copa@rest.com",
                            name = "Copa",
                            perfil = "Copa",
                            senha = "123456"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
